# Generated by Django 5.0.6 on 2024-06-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_is_available_book_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
